# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "exalted_math"
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Stott"]
  s.date = "2012-05-13"
  s.description = "Parsing and evaluation of simple maths expressions for Exalted\n\nThis intended to aid in evaluating simple calculations which appear on character sheets, especially for Exalted."
  s.email = "jonathan.stott@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "exalted_math.gemspec",
    "lib/exalted_math.rb",
    "lib/exalted_math/math.rb",
    "lib/exalted_math/math.treetop",
    "lib/exalted_math/node.rb",
    "lib/exalted_math/node/add.rb",
    "lib/exalted_math/node/divide.rb",
    "lib/exalted_math/node/list.rb",
    "lib/exalted_math/node/maximum.rb",
    "lib/exalted_math/node/minimum.rb",
    "lib/exalted_math/node/multiply.rb",
    "lib/exalted_math/node/named.rb",
    "lib/exalted_math/node/node.rb",
    "lib/exalted_math/node/number.rb",
    "lib/exalted_math/node/operator.rb",
    "lib/exalted_math/node/subtract.rb",
    "script/benchmark.rb",
    "spec/node_spec.rb",
    "spec/parser_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/namelessjon/exalted_math"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Parsing and evaluation of simple maths expressions for Exalted"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, ["~> 1.4"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, ["~> 1.4"])
      s.add_dependency(%q<bacon>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, ["~> 1.4"])
    s.add_dependency(%q<bacon>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

